### PR TITLE
Test coverage and warning fix

### PR DESCRIPTION
**Pull request by gps2601**

### CODE REVIEW

**Review by HelenHTech — DISMISSED** [review]
Great changes Geoff!

**Review by peterjcole — DISMISSED** [review]
⚠️ 🔨

**Review by peterjcole — DISMISSED** [review]
👍

**Review by anthony-hull — DISMISSED** [review]

**Review by AnnaWeakclaw — APPROVED** [review]

**Review by HelenHTech — APPROVED** [review]
Great changes. Middleware looks great

**Pull request merged**
