### PR TITLE
Mapbox migration refactor

### PR DESCRIPTION
**Pull request by anthony-hull**

### CODE REVIEW

**Review by HelenHTech — DISMISSED** [review]
Great changes. Fingers crossed for Mapbox!
Thanks for running through the changes

**Review by AnnaWeakclaw — DISMISSED** [review]
Let's switch then 👍

**Review by peterjcole — COMMENTED** [review]
🗺

**Review by peterjcole — APPROVED** [review]

**Review by HelenHTech — APPROVED** [review]
Looks great

**Pull request merged**
